import type { ExploreItem } from "../types";

export const exploreItems: ExploreItem[] = [
  {
    id: "coffee-break-name",
    title: "Now: ¿Cómo te llamas?",
    level: "pre-a1",
    duration: "Short video",
    type: "Video",
    topic: "Name and first introduction",
    variant: "Spain",
    category: "Watch",
    provider: "Coffee Break Spanish To Go",
    url: "https://coffeebreaklanguages.com/2018/06/como-te-llamas-introducing-yourself-in-spanish-coffee-break-spanish-to-go-episode-1-01-2/",
    description: "Directly matches your current lesson: people answer ¿Cómo te llamas?",
    useFor: "Watch once, then repeat only: Me llamo... / Soy... / ¿Y tú?",
    access: "Free",
    learnerNote: "This is the best first Explore video for your current stage."
  },
  {
    id: "coffee-break-how-are-you",
    title: "Now: ¿Cómo estás?",
    level: "pre-a1",
    duration: "Short video",
    type: "Video",
    topic: "State and greeting",
    variant: "Spain",
    category: "Watch",
    provider: "Coffee Break Spanish To Go",
    url: "https://coffeebreaklanguages.com/2018/07/como-estas-asking-how-are-you-in-spanish-coffee-break-spanish-to-go-episode-1-02/",
    description: "Directly matches your current lesson: people answer ¿Cómo estás?",
    useFor: "Listen for short answers: bien, muy bien, estoy bien. Repeat one answer aloud.",
    access: "Free",
    learnerNote: "Do this after the name video, not before."
  },
  {
    id: "coffee-break-origin",
    title: "Now: ¿De dónde eres?",
    level: "pre-a1",
    duration: "Short video",
    type: "Video",
    topic: "Origin",
    variant: "Spain",
    category: "Watch",
    provider: "Coffee Break Spanish To Go",
    url: "https://coffeebreaklanguages.com/2018/08/de-donde-eres-saying-where-youre-from-in-spanish-coffee-break-spanish-to-go-episode-1-03/",
    description: "Directly matches your current lesson: people answer where they are from.",
    useFor: "Listen for Soy de... and ignore the rest. Then say your own sentence.",
    access: "Free",
    learnerNote: "Use this when Day 3 or Day 7 feels familiar."
  },
  {
    id: "coffee-break-spanish",
    title: "Later: Coffee Break Spanish 1.01",
    level: "pre-a1",
    duration: "12 min",
    type: "Podcast",
    topic: "Guided beginner listening",
    variant: "Spain",
    category: "Listen",
    provider: "Coffee Break Languages",
    url: "https://shows.acast.com/coffeebreakspanish/episodes/season-1-lesson-01-coffee-break-spanish",
    description: "A teacher-guided beginner podcast lesson for hello and basic feelings.",
    useFor: "Use it when you want explanations in English and slower practice.",
    access: "Free",
    learnerNote: "Good backup if the videos feel too fast."
  },
  {
    id: "dreaming-spanish-superbeginner",
    title: "Later: Dreaming Spanish Superbeginner",
    level: "pre-a1",
    duration: "5-15 min",
    type: "Video",
    topic: "Comprehensible input",
    variant: "Mixed",
    category: "Watch",
    provider: "Dreaming Spanish",
    url: "https://www.dreamingspanish.com/browse?level=superbeginner",
    description: "Visual, slow Spanish videos designed for comprehensible input.",
    useFor: "Use this after your current first-conversation lessons feel less fragile.",
    access: "Free/Paid",
    learnerNote: "Choose Superbeginner only. Do not use random harder videos yet."
  },
  {
    id: "duolingo-spanish-podcast",
    title: "Later: Duolingo Spanish Podcast",
    level: "a1",
    duration: "15-25 min",
    type: "Podcast",
    topic: "Bilingual stories",
    variant: "Latin America",
    category: "Listen",
    provider: "Duolingo",
    url: "https://podcast.duolingo.com/spanish",
    description: "Spanish stories supported by English narration, often easier than fully native podcasts.",
    useFor: "Use after you finish more daily lessons, not as today's first input.",
    access: "Free",
    learnerNote: "This is not current-stage core input yet. Save it for later listening stamina."
  },
  {
    id: "easy-spanish-podcast",
    title: "Easy Spanish Podcast",
    level: "a1",
    duration: "15-30 min",
    type: "Podcast",
    topic: "Natural conversation",
    variant: "Mixed",
    category: "Listen",
    provider: "Easy Spanish",
    url: "https://www.easyspanish.fm/",
    description: "Real conversations for learners, useful once Day 1-7 chunks feel familiar.",
    useFor: "Listen for greetings, turn-taking, and common phrases rather than understanding every word.",
    access: "Free/Paid",
    learnerNote: "Use short sections only; this is better as repeated exposure than a test."
  },
  {
    id: "easy-spanish-youtube",
    title: "Easy Spanish",
    level: "a1",
    duration: "5-15 min",
    type: "Video",
    topic: "Street interviews",
    variant: "Mixed",
    category: "Watch",
    provider: "Easy Languages",
    url: "https://www.youtube.com/@EasySpanish",
    description: "Street interviews and learner videos with subtitles.",
    useFor: "Notice how people answer simple questions in real speech.",
    access: "Free",
    learnerNote: "Use subtitles as support; shadow one useful sentence, not the whole video."
  },
  {
    id: "why-not-spanish",
    title: "Why Not Spanish?",
    level: "a1",
    duration: "5-15 min",
    type: "Video",
    topic: "Latin American Spanish",
    variant: "Latin America",
    category: "Watch",
    provider: "Why Not Spanish?",
    url: "https://www.youtube.com/@WhyNotSpanish",
    description: "Spanish learning videos with Colombian and broadly Latin American usage.",
    useFor: "Use for pronunciation, common phrases, and learner-friendly explanations.",
    access: "Free",
    learnerNote: "Pick videos that match your current Can-Do, such as introductions or daily life."
  },
  {
    id: "filminlatino",
    title: "FilminLatino",
    level: "a1",
    duration: "Film length",
    type: "Movie",
    topic: "Mexican cinema",
    variant: "Mexico",
    category: "Movie",
    provider: "IMCINE / FilminLatino",
    url: "https://www.filminlatino.mx/",
    description: "Mexican film platform with independent films and cultural content.",
    useFor: "Use trailers, descriptions, and short scenes as cultural input before full movies.",
    access: "May need account",
    learnerNote: "Full films are not beginner material; start with titles, posters, trailers, and repeated scenes."
  },
  {
    id: "rtve-play-cine",
    title: "RTVE Play Cine",
    level: "a1",
    duration: "Film length",
    type: "Movie",
    topic: "Spanish cinema",
    variant: "Spain",
    category: "Movie",
    provider: "RTVE",
    url: "https://www.rtve.es/play/cine/",
    description: "Official Spanish public broadcaster film catalog.",
    useFor: "Use as an official legal source for Spanish-language films and clips.",
    access: "Region may vary",
    learnerNote: "Spain-specific accents are normal variants, not wrong Spanish. Use subtitles when available."
  },
  {
    id: "filmoteca-unam",
    title: "Filmoteca UNAM",
    level: "a1",
    duration: "Varies",
    type: "Culture",
    topic: "Mexican film culture",
    variant: "Mexico",
    category: "Movie",
    provider: "UNAM",
    url: "https://www.filmoteca.unam.mx/",
    description: "Official Mexican university film archive with cultural programming and film information.",
    useFor: "Explore Mexican film titles, descriptions, festivals, and cultural context.",
    access: "Free",
    learnerNote: "Good for browsing names, places, genres, and short descriptions rather than full beginner lessons."
  }
];
