import type { ExploreItem } from "../types";

export const exploreItems: ExploreItem[] = [
  {
    id: "dreaming-spanish-superbeginner",
    title: "Start here: Where Is the Bathroom?",
    level: "pre-a1",
    duration: "8 min",
    type: "Video",
    topic: "Comprehensible input",
    variant: "Mixed",
    category: "Watch",
    provider: "Dreaming Spanish",
    url: "https://app.dreaming.com/spanish/watch?id=6a290eff09d2527916e040e6",
    description: "A specific Superbeginner video you can open and watch immediately.",
    useFor: "Best first click. Watch once for meaning, then watch again and repeat any line you recognize.",
    access: "Free/Paid",
    learnerNote: "If Dreaming Spanish asks you to log in, use the free account path or switch to Coffee Break below."
  },
  {
    id: "coffee-break-spanish",
    title: "Start here: Coffee Break Spanish 1.01",
    level: "pre-a1",
    duration: "12 min",
    type: "Podcast",
    topic: "Guided beginner listening",
    variant: "Spain",
    category: "Listen",
    provider: "Coffee Break Languages",
    url: "https://shows.acast.com/coffeebreakspanish/episodes/season-1-lesson-01-coffee-break-spanish",
    description: "The first free Coffee Break Spanish episode: hello and how you are feeling.",
    useFor: "Best first listening session. Pause after short Spanish phrases and repeat aloud.",
    access: "Free",
    learnerNote: "Teacher-guided, so it is easier than raw native audio. Accent is Spain, still useful and correct."
  },
  {
    id: "duolingo-spanish-podcast",
    title: "Later: Mi heroe, mi amigo",
    level: "a1",
    duration: "Story",
    type: "Podcast",
    topic: "Bilingual stories",
    variant: "Latin America",
    category: "Listen",
    provider: "Duolingo",
    url: "https://podcast.duolingo.com/introducing-the-duolingo-spanish-podcast-61e07ec8affe",
    description: "A Mexico story with English narration and transcript support.",
    useFor: "Use this after a few days of lessons, when you want a real story with help.",
    access: "Free",
    learnerNote: "This is harder than the first two. Catch names, places and repeated ideas."
  },
  {
    id: "easy-spanish-podcast",
    title: "Easy Spanish Podcast",
    level: "a1",
    duration: "15-30 min",
    type: "Podcast",
    topic: "Natural conversation",
    variant: "Mixed",
    category: "Listen",
    provider: "Easy Spanish",
    url: "https://www.easyspanish.fm/",
    description: "Real conversations for learners, useful once Day 1-7 chunks feel familiar.",
    useFor: "Listen for greetings, turn-taking, and common phrases rather than understanding every word.",
    access: "Free/Paid",
    learnerNote: "Use short sections only; this is better as repeated exposure than a test."
  },
  {
    id: "easy-spanish-youtube",
    title: "Easy Spanish",
    level: "a1",
    duration: "5-15 min",
    type: "Video",
    topic: "Street interviews",
    variant: "Mixed",
    category: "Watch",
    provider: "Easy Languages",
    url: "https://www.youtube.com/@EasySpanish",
    description: "Street interviews and learner videos with subtitles.",
    useFor: "Notice how people answer simple questions in real speech.",
    access: "Free",
    learnerNote: "Use subtitles as support; shadow one useful sentence, not the whole video."
  },
  {
    id: "why-not-spanish",
    title: "Why Not Spanish?",
    level: "a1",
    duration: "5-15 min",
    type: "Video",
    topic: "Latin American Spanish",
    variant: "Latin America",
    category: "Watch",
    provider: "Why Not Spanish?",
    url: "https://www.youtube.com/@WhyNotSpanish",
    description: "Spanish learning videos with Colombian and broadly Latin American usage.",
    useFor: "Use for pronunciation, common phrases, and learner-friendly explanations.",
    access: "Free",
    learnerNote: "Pick videos that match your current Can-Do, such as introductions or daily life."
  },
  {
    id: "filminlatino",
    title: "FilminLatino",
    level: "a1",
    duration: "Film length",
    type: "Movie",
    topic: "Mexican cinema",
    variant: "Mexico",
    category: "Movie",
    provider: "IMCINE / FilminLatino",
    url: "https://www.filminlatino.mx/",
    description: "Mexican film platform with independent films and cultural content.",
    useFor: "Use trailers, descriptions, and short scenes as cultural input before full movies.",
    access: "May need account",
    learnerNote: "Full films are not beginner material; start with titles, posters, trailers, and repeated scenes."
  },
  {
    id: "rtve-play-cine",
    title: "RTVE Play Cine",
    level: "a1",
    duration: "Film length",
    type: "Movie",
    topic: "Spanish cinema",
    variant: "Spain",
    category: "Movie",
    provider: "RTVE",
    url: "https://www.rtve.es/play/cine/",
    description: "Official Spanish public broadcaster film catalog.",
    useFor: "Use as an official legal source for Spanish-language films and clips.",
    access: "Region may vary",
    learnerNote: "Spain-specific accents are normal variants, not wrong Spanish. Use subtitles when available."
  },
  {
    id: "filmoteca-unam",
    title: "Filmoteca UNAM",
    level: "a1",
    duration: "Varies",
    type: "Culture",
    topic: "Mexican film culture",
    variant: "Mexico",
    category: "Movie",
    provider: "UNAM",
    url: "https://www.filmoteca.unam.mx/",
    description: "Official Mexican university film archive with cultural programming and film information.",
    useFor: "Explore Mexican film titles, descriptions, festivals, and cultural context.",
    access: "Free",
    learnerNote: "Good for browsing names, places, genres, and short descriptions rather than full beginner lessons."
  }
];
