import type { ExploreItem } from "../types";

export const exploreItems: ExploreItem[] = [
  {
    id: "coffee-break-spanish",
    title: "Coffee Break Spanish",
    level: "pre-a1",
    duration: "10-20 min",
    type: "Podcast",
    topic: "Guided beginner listening",
    variant: "Spain",
    category: "Listen",
    provider: "Coffee Break Languages",
    url: "https://coffeebreaklanguages.com/coffeebreakspanish/",
    description: "Structured beginner-friendly podcast lessons with explanations in English.",
    useFor: "Use it when you want a teacher-guided listening session instead of raw native audio.",
    access: "Free/Paid",
    learnerNote: "Start with early episodes; pause after short chunks and repeat the Spanish aloud."
  },
  {
    id: "easy-spanish-podcast",
    title: "Easy Spanish Podcast",
    level: "a1",
    duration: "15-30 min",
    type: "Podcast",
    topic: "Natural conversation",
    variant: "Mixed",
    category: "Listen",
    provider: "Easy Spanish",
    url: "https://www.easyspanish.fm/",
    description: "Real conversations for learners, useful once Day 1-7 chunks feel familiar.",
    useFor: "Listen for greetings, turn-taking, and common phrases rather than understanding every word.",
    access: "Free/Paid",
    learnerNote: "Use short sections only; this is better as repeated exposure than a test."
  },
  {
    id: "duolingo-spanish-podcast",
    title: "Duolingo Spanish Podcast",
    level: "a1",
    duration: "15-25 min",
    type: "Podcast",
    topic: "Bilingual stories",
    variant: "Latin America",
    category: "Listen",
    provider: "Duolingo",
    url: "https://podcast.duolingo.com/spanish",
    description: "Spanish stories supported by English narration, often easier than fully native podcasts.",
    useFor: "Build listening stamina and notice familiar words inside meaningful stories.",
    access: "Free",
    learnerNote: "Do not worry about full comprehension; catch names, places, emotions, and repeated phrases."
  },
  {
    id: "dreaming-spanish-superbeginner",
    title: "Dreaming Spanish",
    level: "pre-a1",
    duration: "5-15 min",
    type: "Video",
    topic: "Comprehensible input",
    variant: "Mixed",
    category: "Watch",
    provider: "Dreaming Spanish",
    url: "https://www.dreamingspanish.com/browse?level=superbeginner",
    description: "Visual, slow Spanish videos designed for comprehensible input.",
    useFor: "Watch without translating; use visuals and repeated words to understand the situation.",
    access: "Free/Paid",
    learnerNote: "Choose Superbeginner first. One short video repeated twice is better than browsing many."
  },
  {
    id: "easy-spanish-youtube",
    title: "Easy Spanish",
    level: "a1",
    duration: "5-15 min",
    type: "Video",
    topic: "Street interviews",
    variant: "Mixed",
    category: "Watch",
    provider: "Easy Languages",
    url: "https://www.youtube.com/@EasySpanish",
    description: "Street interviews and learner videos with subtitles.",
    useFor: "Notice how people answer simple questions in real speech.",
    access: "Free",
    learnerNote: "Use subtitles as support; shadow one useful sentence, not the whole video."
  },
  {
    id: "why-not-spanish",
    title: "Why Not Spanish?",
    level: "a1",
    duration: "5-15 min",
    type: "Video",
    topic: "Latin American Spanish",
    variant: "Latin America",
    category: "Watch",
    provider: "Why Not Spanish?",
    url: "https://www.youtube.com/@WhyNotSpanish",
    description: "Spanish learning videos with Colombian and broadly Latin American usage.",
    useFor: "Use for pronunciation, common phrases, and learner-friendly explanations.",
    access: "Free",
    learnerNote: "Pick videos that match your current Can-Do, such as introductions or daily life."
  },
  {
    id: "filminlatino",
    title: "FilminLatino",
    level: "a1",
    duration: "Film length",
    type: "Movie",
    topic: "Mexican cinema",
    variant: "Mexico",
    category: "Movie",
    provider: "IMCINE / FilminLatino",
    url: "https://www.filminlatino.mx/",
    description: "Mexican film platform with independent films and cultural content.",
    useFor: "Use trailers, descriptions, and short scenes as cultural input before full movies.",
    access: "May need account",
    learnerNote: "Full films are not beginner material; start with titles, posters, trailers, and repeated scenes."
  },
  {
    id: "rtve-play-cine",
    title: "RTVE Play Cine",
    level: "a1",
    duration: "Film length",
    type: "Movie",
    topic: "Spanish cinema",
    variant: "Spain",
    category: "Movie",
    provider: "RTVE",
    url: "https://www.rtve.es/play/cine/",
    description: "Official Spanish public broadcaster film catalog.",
    useFor: "Use as an official legal source for Spanish-language films and clips.",
    access: "Region may vary",
    learnerNote: "Spain-specific accents are normal variants, not wrong Spanish. Use subtitles when available."
  },
  {
    id: "filmoteca-unam",
    title: "Filmoteca UNAM",
    level: "a1",
    duration: "Varies",
    type: "Culture",
    topic: "Mexican film culture",
    variant: "Mexico",
    category: "Movie",
    provider: "UNAM",
    url: "https://www.filmoteca.unam.mx/",
    description: "Official Mexican university film archive with cultural programming and film information.",
    useFor: "Explore Mexican film titles, descriptions, festivals, and cultural context.",
    access: "Free",
    learnerNote: "Good for browsing names, places, genres, and short descriptions rather than full beginner lessons."
  }
];
