import type { VocabItem } from "../types";

const today = new Date().toISOString();

export const initialVocabulary: VocabItem[] = [
  {
    id: "hola",
    term: "Hola.",
    meaning: "Hello.",
    meaningZh: "你好。",
    lessonId: "day-1-hola",
    status: "LEARNING",
    strength: 35,
    lastSeen: null,
    nextReview: today,
    correctStreak: 0,
    wrongCount: 0,
    productionScore: 0,
    listeningScore: 0,
    contextScore: 0
  },
  {
    id: "buenos-dias",
    term: "Buenos días.",
    meaning: "Good morning.",
    meaningZh: "早上好。",
    lessonId: "day-1-hola",
    status: "NEW",
    strength: 15,
    lastSeen: null,
    nextReview: today,
    correctStreak: 0,
    wrongCount: 0,
    productionScore: 0,
    listeningScore: 0,
    contextScore: 0
  },
  {
    id: "buenas-tardes",
    term: "Buenas tardes.",
    meaning: "Good afternoon.",
    meaningZh: "下午好。",
    lessonId: "day-1-hola",
    status: "NEW",
    strength: 12,
    lastSeen: null,
    nextReview: today,
    correctStreak: 0,
    wrongCount: 0,
    productionScore: 0,
    listeningScore: 0,
    contextScore: 0
  },
  {
    id: "buenas-noches",
    term: "Buenas noches.",
    meaning: "Good evening / Good night.",
    meaningZh: "晚上好 / 晚安。",
    lessonId: "day-1-hola",
    status: "NEW",
    strength: 12,
    lastSeen: null,
    nextReview: today,
    correctStreak: 0,
    wrongCount: 0,
    productionScore: 0,
    listeningScore: 0,
    contextScore: 0
  },
  {
    id: "me-llamo",
    term: "Me llamo...",
    meaning: "My name is...",
    meaningZh: "我叫……",
    lessonId: "day-1-hola",
    status: "LEARNING",
    strength: 28,
    lastSeen: null,
    nextReview: today,
    correctStreak: 1,
    wrongCount: 0,
    productionScore: 0,
    listeningScore: 0,
    contextScore: 0
  },
  {
    id: "soy",
    term: "Soy...",
    meaning: "I am...",
    meaningZh: "我是……",
    lessonId: "day-1-hola",
    status: "FAMILIAR",
    strength: 52,
    lastSeen: null,
    nextReview: today,
    correctStreak: 2,
    wrongCount: 0,
    productionScore: 0,
    listeningScore: 0,
    contextScore: 0
  },
  {
    id: "mucho-gusto",
    term: "Mucho gusto.",
    meaning: "Nice to meet you.",
    meaningZh: "很高兴认识你。",
    lessonId: "day-1-hola",
    status: "ACTIVE",
    strength: 68,
    lastSeen: null,
    nextReview: today,
    correctStreak: 3,
    wrongCount: 0,
    productionScore: 0,
    listeningScore: 0,
    contextScore: 0
  },
  {
    id: "y-tu",
    term: "¿Y tú?",
    meaning: "And you?",
    meaningZh: "你呢？",
    lessonId: "day-1-hola",
    status: "NEW",
    strength: 18,
    lastSeen: null,
    nextReview: today,
    correctStreak: 0,
    wrongCount: 0,
    productionScore: 0,
    listeningScore: 0,
    contextScore: 0
  },
  {
    id: "como-te-llamas",
    term: "¿Cómo te llamas?",
    meaning: "What is your name?",
    meaningZh: "你叫什么名字？",
    lessonId: "day-1-hola",
    status: "NEW",
    strength: 12,
    lastSeen: null,
    nextReview: today,
    correctStreak: 0,
    wrongCount: 0,
    productionScore: 0,
    listeningScore: 0,
    contextScore: 0
  },
  {
    id: "encantado",
    term: "Encantado.",
    meaning: "Nice to meet you. (masculine)",
    meaningZh: "很高兴认识你。（男性说法）",
    lessonId: "day-1-hola",
    status: "NEW",
    strength: 12,
    lastSeen: null,
    nextReview: today,
    correctStreak: 0,
    wrongCount: 0,
    productionScore: 0,
    listeningScore: 0,
    contextScore: 0
  },
  {
    id: "encantada",
    term: "Encantada.",
    meaning: "Nice to meet you. (feminine)",
    meaningZh: "很高兴认识你。（女性说法）",
    lessonId: "day-1-hola",
    status: "NEW",
    strength: 12,
    lastSeen: null,
    nextReview: today,
    correctStreak: 0,
    wrongCount: 0,
    productionScore: 0,
    listeningScore: 0,
    contextScore: 0
  },
  {
    id: "gracias",
    term: "Gracias.",
    meaning: "Thank you.",
    meaningZh: "谢谢。",
    lessonId: "day-1-hola",
    status: "NEW",
    strength: 12,
    lastSeen: null,
    nextReview: today,
    correctStreak: 0,
    wrongCount: 0,
    productionScore: 0,
    listeningScore: 0,
    contextScore: 0
  }
];
